import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import Providers from "./provider";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const pretendard = localFont({
	src: "../static/fonts/PretendardVariable.woff2",
	display: "swap",
	weight: "45 920",
	variable: "--font-pretendard",
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={`${pretendard.variable}`}>
			<body>
				<div className="root-container">
					<Providers>{children}</Providers>
				</div>
			</body>
		</html>
	);
}
